language: rust
cache: cargo
rust:
  - nightly

addons:
  ssh_known_hosts: scarletbus.com

before_install:
  - openssl aes-256-cbc -K $encrypted_70ba39ff6889_key -iv $encrypted_70ba39ff6889_iv -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa

script: ./test.sh

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh